language: java
services:
  - postgresql
before_script:
  - psql -c 'create user ords superuser;' -U postgres
  - psql -c 'create database ordstest owner ords;' -U postgres

after_success:
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings settings.xml

env:
  global:
    - secure: "EOakXJpALjzY5NQx7rNo0kdmqJ55sJxHVV5GLS4hQJdNDt0hiyKHol8i9oKinH+zGPSIJ5RxQij6worMr9BdJyPifQjpOkNu9uoxGQ4Tw8nl5h6Y82RG1SRjdNFMP81tPzzirWbgnfMsuSlMzSELneNjSa91K3XrNnPSoo6cLzg/U5qLNeRgN791oWYhe5NFJd9a8+awfP0zFDBkj6B8ow6SeR8ya9/0oXJiYDJmExaD1ZgL2MNS9/Sa7Dh9sxAwaVSXrLOkyDg00zJ/LJ9GYmYl8fyy6Y7C/4cQSO16MhHLJogXJwhLbVa8XCd2HD6Ot3SushWDYRSNjCaAjPzH2PAj7lYISafF/VkRF4DvHzOv6nL1Mv/6trpmc4EP6hGZoPMkQW6aZk1sBLi/e5PZvm6ZK0HpOxr8oESPGNfxRg3azz21tiFWSrTNM9Pp1Iy8oDjlGdaRLmwY2whiKGBM7PrE4kteS7UDm4s2MkbDZgXIaH4nsHO8UTjOVnQhdivzmGekb62ju3KF/0NAkHWVFLham9yvz/3/eCewRZHeLMQ987oxFx7LsVA0JU77arkAmgOd2YyIClquwBKFvht1g0HDRek53JDU4N1THAjHto07aSm39hyCpXT7kXhfLdT7hzcXpAGQc77yYkq7OihAy50h1jadaVVxN5glKuvZyzE="
    - secure: "VApQbWINADaihpXY0SePHCerSI6Gw4OCnogFp5SKwxHewjqNKkX0B4khll0mTwfIJ1okgCfJKiwuFr1z7XC5DvR+JF3KP8JBAguMhKpFr47Otu9QBqXCS7d3BTbASix0dRnQlvjhFA4j5amZg1u081rQk0ho/ey6YfV9PEGC2M4BoIt9LfKenKtnBLJULCxhVpAPCEaVvPPzwafmP3rEd9lyrHNauYyoHAqlOl/DNDSLovyDHypuc2EjcPVFXcr7PCcw5uHA/19MQL/cFZJpsSJE3fkcTeqIylmdmjHo4J6yiSQMnywLVQJ/10TIJ5xNrq2/AQK90tUFzhTC6VpU9TWEOvtqrpa7WZ4zSutoKiIMBudAGD8kPa1eVAHvOaCJK8z1aKaUVYsYqckYe53K5RDI8Bk7yvcdEgIthMSh/bnSDlzx9b1Dkbv9XXTKMj2wdEG8hJ71fijBjYap2g1A29yrIFYF6MVXa41N2exC0Lse8FwEZKTA5buRwuWo2Xc5ybX3ob8wzeowzGYA+KCldPxulbnZ8hlBOxL/N+hNH2PH3qhCUiZji2DN5hKXWlkQewc7isteHudhn52Qm+K64oPD1/qntnVPx4KKHA+MyeQ+h+LraxX07TOpjEYHBF0nS/+lCusCg/P/8ZxWLllh6s+drhhfrcclqFRojSkzd8I="
  